version: '3'
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/postgres -user=postgres -password=P@ssw0rd -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/migrations:/flyway/sql
    depends_on:
      - db
  db:
    image: postgres:12.2
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
    ports:
      - 5432:5432