version: '3'
services:
  flyway:
    image: flyway/flyway:6.4
    command: -url=jdbc:postgresql://db/postgres -user=postgres -password=P@ssw0rd -schemas=public,keycloak -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/migrations:/flyway/sql
    depends_on:
      - db
  db:
    image: postgres:12.2
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
    ports:
      - 5432:5432
  keycloak:
    image: jboss/keycloak:10.0.0
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_SCHEMA: keycloak
      DB_PASSWORD: P@ssw0rd
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
    ports:
      - 8080:8080
    depends_on:
      - flyway